name: Create Issues from MD files

on:
  workflow_dispatch:

jobs:
  create-issues:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create issues
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          chmod +x create-issues.sh
          ./create-issues.sh ${{ github.repository }}
